language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "GraceShopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: tigerwines # see README
  api_key:
    secure: fSbQo8yOc/9Txux9PGutiO30B6HJgYypdBUB80eZ8Cl5RszVR269BCKqxfX+Sv7HilXu1eeqBlepAnPSm6zNLWvDh9HwWgf4ICwlAhpC9Jy9Rx/I4GjJHRRku2UYd6RfLcQH9A/dAOp3RTMtjBVjb6tSre6Lz3GmK5nV0K4zm5ypKxu78WiPj7ER9fHiW1p7GgF+vUtzVpTkUeEDbz6yOCB3TjcSXhB4UONrd3B9LSbBnLvOoz1ypdfWTvb+ajt1KVeyyx+SQYyEpgFHR7pYYxZDi916IkWXUuaZCEjCqijY11PIVzDfqHFYiZg9K6nh28tMTZtihP3IrPqBSpIAd8Lc2z+/m75Vd/rrHuwKrxvcFaZk74FrbXTczzZ2WkKu1ETDVU6N7Okpnodw6Ks3jlt8VMicoNwnuy2KUZ4iqpTaJinxZrzMIRGyCErgg+AEiG1BYOvVnYcgqNlDGRYOmg0YQwI5gpKm5xjzATk3JKNk25qkdvt1ArKBv02tlQow7sPdoVb+vs+QZFBQdQLG6uOd35fwcg6TDgnSicSSbq/EZh7jD3ow31TFOCKNBAxUyu3jtd0Wxaut9prrSPbG0e6Omvwc/4KK6nu/bbC9XmjBvokTYNvnIx0AJ+W4xcUH/h3BY0cDSC8O+hYBZkcyATGe1Gto9Z9aCgINHIaeOYY=
