language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "GraceShopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: tigerwines # see README
 api_key:
    secure: ZwMeFr9o8f2CtizbIRpF6eMsvOff2o/IWhPpi6RrtLURl5sBqTftD6OY6l3ijomALLWkuUJlXT66IiU097g4wsdSwWyAdr/f+h5n5pjDdjXyU25FMf8zGKzMY90eMVdDygsM5FIDLXAm6zetuPobADPBE+g9vndE2iO6frBvogmtt1gB4QE4J5+afmt70HE106j08eISrGXjaNemfZcsaN22aF4+CY0l3wvwPus0m7PBQLSoprlavQ/WlfQMnsN9KYNNiZDRvjF+u72f+CXTL461fvCej88e/9Bx2+XvVCvmZhSaeFcrU0eXYMHQuybIHcU9/DZNdLFCTARypnDcjWvELjLX4/gEGoy6YeLQXwj76bq9W9fnC0UgArl+arGA0tgWN4aiFCfQ+FFp/vm/MNL6YFyoGLB+bchxmUGnvSrjd/wMWyyd+M8WPRzmNvlY7C23gb6AKnwLlPOHjDyDm8tVP/wXpf5WRPSYs4chEMozaTly3iB2DfaNGvoHHHX/COzrhht6EUwmJEh9Oqx1i2xa3DQadsw00OUomfEhEwI6TR+hCyZURlW4szA5EoLvCaKLxKAyXiqY4rVyyUsjXIzi8ll0r1rtvwVdgJJ82FnS/9haA4D7W5y0zbtd0/HAS4Q4CX+EFKoT8CuW7jedsg/E8tk+MwQ5TQN4CVkxCC8=